### ISSUE TITLE
ERROR: relation "user_id" already exists

### ISSUE THREAD

**Issue by IoTree** [nextcloud/cms_pico#187] opened 2021-12-20 20:27 UTC
Hello,
I have a fresh nextcloud installation 23.0.0
With apps installed: talk, libreoffice, audio-player, cookbook, calendar, contacts and preinstalled apps...

I wanted to install the pico cms to create a blog, unfortunately an error occurs at installation that says:
"An exception occurred while executing a query: SQLSTATE[42P07]: Duplicated table: 7 ERROR: Relation "user_id" already exists"

other applications verified for 23.0.0 working fine.
It could be a problem similar to this one.
https://github.com/nextcloud/server/issues/29986

if you need further information feel free to contact.

**Comment by PhrozenByte** [comment] 2021-12-20 20:36
A fix is currently in the making, please stay tuned.

Duplicate of #186

**Closed by PhrozenByte** 2021-12-20 20:36 UTC
Labels: type: Duplicate

**Comment by PhrozenByte** [comment] 2022-01-17 12:56
Should be fixed now, please try cms_pico's latest version v1.0.17.
