### ISSUE TITLE
NC18 fails with cms_pico enabled

### ISSUE THREAD

**Issue by versd** [nextcloud/cms_pico#112] opened 2020-01-27 12:49 UTC
I've been running NC17 and picocms without problems. After updating to NC18 the problems started; When I enable PicoCMS the nextcloud 18 instance becomes unavailable (only get an error page). It gives this stacktrace in the logs:

```
[webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable: TypeError: Argument 1 passed to OCA\CMSPico\AppInfo\Application::OCA\CMSPico\AppInfo\{closure}() must be an instance of Symfony\Component\EventDispatcher\Event, instance of OCP\EventDispatcher\GenericEvent given, called in /usr/share/webapps/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php on line 247 at <<closure>>

0. <<closure>>
   {closure}("*** sensitive parameters replaced ***")
1. /usr/share/webapps/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
   call_user_func_array(Closure {}, ["*** sensitive  ... "])
2. /usr/share/webapps/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 466
   Sabre\Event\EventEmitter->emit("beforeMethod", ["*** sensitive  ... "])
3. /usr/share/webapps/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
   Sabre\DAV\Server->invokeMethod("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
4. /usr/share/webapps/nextcloud/remote.php line 74
   Sabre\DAV\Server->exec()
5. /usr/share/webapps/nextcloud/remote.php line 170
   handleException(TypeError {})

PROPFIND /remote.php/dav/files/<username>/
```

After disabling the app from commandline the nextcloud instance is available again.

**Comment by PhrozenByte** [comment] 2020-01-27 17:08
Duplicate of #110

**Closed by PhrozenByte** 2020-01-27 17:08 UTC
Labels: type: Duplicate
