### ISSUE TITLE
An exception occurred while executing a query: SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "user_id" already exists

### ISSUE THREAD

**Issue by traverseda** [nextcloud/cms_pico#189] opened 2022-01-10 15:54 UTC
I'm assessing this for a client, and unfortunately the above error shows up whenever I try to install this plugin.

I ran `./occ maintenance:repair` and am getting the same error. Using `Nextcloud Hub II (23.0.0)` on docker.

**Comment by PhrozenByte** [comment] 2022-01-10 22:08
Duplicate of #186

**Closed by PhrozenByte** 2022-01-10 22:08 UTC

**Comment by PhrozenByte** [comment] 2022-01-17 12:56
Should be fixed now, please try cms_pico's latest version v1.0.17.

**Comment by traverseda** [comment] 2022-01-17 13:27
Can confirm that it's working
