### ISSUE TITLE
Upgrade to NC version 23 failes because of index name duplication

### ISSUE THREAD

**Issue by dermalikmann** [nextcloud/cms_pico#188] opened 2022-01-05 15:09 UTC
[Here](https://github.com/nextcloud/cms_pico/blob/c158a577039a7ead616192c159145385e4500933/lib/Migration/Version010000.php#L112) this addon creates an index.

This index name creates issues with the latest db migration when upgrading to NC 23. It is probably the cause of nextcloud/server#30226

**Comment by PhrozenByte** [comment] 2022-01-05 18:37
Duplicate of #186

**Closed by PhrozenByte** 2022-01-05 18:37 UTC
Labels: type: Duplicate

**Comment by PhrozenByte** [comment] 2022-01-17 12:56
Should be fixed now, please try cms_pico's latest version v1.0.17.
