### ISSUE TITLE
/index.php/apps/cms_pico/pico/undefined/img/notifications-new.svg not found

### ISSUE THREAD

**Issue by fermat2a** [nextcloud/cms_pico#131] opened 2020-06-06 16:10 UTC
Hi,

I am running Nextcloud 18.0.5 with your Pico CMS 1.0.6 app. I tried to create a web page using the template sample_pico but I only get an error page when I try to access it. In the apache logs I found following:

192.168.135.55 - - [06/Jun/2020:18:01:55 +0200] "GET /index.php/apps/cms_pico/pico/admin_test/undefined/img/notifications-new.svg HTTP/1.1" 500 7576 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
192.168.135.55 - - [06/Jun/2020:18:01:55 +0200] "GET /index.php/apps/cms_pico/pico/admin_test/undefined/img/notifications-new.svg HTTP/1.1" 500 7001 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"

Is there a problem in combination with the Notifications app? I have installed it in version 2.6.0.

bests

Sascha

**Comment by PhrozenByte** [comment] 2020-06-07 09:37
Check your Nextcloud logs and please provide the actual error message.

**Comment by fermat2a** [comment] 2020-06-07 13:23
Good idea... :-) I see following error:

[index] Error: Exception: Call to undefined method ParsedownExtra::textElements() at <<closure>>

0. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\CMSPico\Controller\PicoController {}, "getPage")
1. /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\CMSPico\\C ... r", "getPage", OC\AppFramework\ ... {}, {page: "",site:  ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({page: "",site:  ... "})
3. /var/www/html/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {page: "",site:  ... "})
4. /var/www/html/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/cms_pico/pico/admin_test")
5. /var/www/html/nextcloud/index.php line 38
   OC::handleRequest()

GET /index.php/apps/cms_pico/pico/admin_test
from 192.168.135.175 by admin at 2020-06-07T13:21:54+00:00

**Comment by PhrozenByte** [comment] 2020-06-07 13:40
Duplicate of #97

**Closed by PhrozenByte** 2020-06-07 13:40 UTC
Labels: type: Question

**Comment by fermat2a** [comment] 2020-06-07 15:38
Thanks, disabling the "Issue Template" App helped for me also.

Do you think it might make sense to place this information in the wiki? Something like "Conflicting Apps"? Or a page Troubleshooting? If you tell me you will not delete directly I would add it...

**Comment by PhrozenByte** [comment] 2020-06-07 21:11
Since there are a lot of people experiencing this issue recently it's probably a good idea to include a notice in the app's admin settings. See 13e334d9643c83465cc1acc568c5d7db4ebc4706. I'll create a new release in a few days (waiting for translations first).

**Comment by fermat2a** [comment] 2020-06-08 05:28
Even better than wiki, thanks.
